filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Rafael, Welcome to Coot version 0.8.9.2")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good morning Rafael. Welcome to Coot 0.8.9.2")
set_display_lists_for_maps (0)
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (12.60)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
handle_read_draw_molecule_with_recentre ("ALA-trial1.pdb", 0)
handle_read_draw_molecule_with_recentre ("ASN/ASN_m120.pdb", 0)
handle_read_draw_molecule_with_recentre ("ASN/ASN_m-20.pdb", 0)
handle_read_draw_molecule_with_recentre ("ASN/ASN_m-80.pdb", 0)
handle_read_draw_molecule_with_recentre ("ASN/ASN_p-10.pdb", 0)
handle_read_draw_molecule_with_recentre ("ASN/ASN_p30.pdb", 0)
handle_read_draw_molecule_with_recentre ("ASN/ASN_t-20.pdb", 0)
handle_read_draw_molecule_with_recentre ("ASN/ASN_t30.pdb", 0)
use_graphics_interface_state ()
