(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Rafael, Welcome to Coot version 0.8.9.2")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good morning Rafael. Welcome to Coot 0.8.9.2")
(set-display-lists-for-maps 0)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 12.60)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(handle-read-draw-molecule-with-recentre "ALA-trial1.pdb" 0)
(handle-read-draw-molecule-with-recentre "ASN/ASN_m120.pdb" 0)
(handle-read-draw-molecule-with-recentre "ASN/ASN_m-20.pdb" 0)
(handle-read-draw-molecule-with-recentre "ASN/ASN_m-80.pdb" 0)
(handle-read-draw-molecule-with-recentre "ASN/ASN_p-10.pdb" 0)
(handle-read-draw-molecule-with-recentre "ASN/ASN_p30.pdb" 0)
(handle-read-draw-molecule-with-recentre "ASN/ASN_t-20.pdb" 0)
(handle-read-draw-molecule-with-recentre "ASN/ASN_t30.pdb" 0)
(use-graphics-interface-state)
