mutate (0,"A",1,"","VAL")
set_residue_to_rotamer_name (0,"A",1,"","","p")
write_pdb_file (0,"/home/jbruno/PycharmProjects/SLIDER/aa/VAL/VAL_p.pdb")
set_residue_to_rotamer_name (0,"A",1,"","","t")
write_pdb_file (0,"/home/jbruno/PycharmProjects/SLIDER/aa/VAL/VAL_t.pdb")
set_residue_to_rotamer_name (0,"A",1,"","","m")
write_pdb_file (0,"/home/jbruno/PycharmProjects/SLIDER/aa/VAL/VAL_m.pdb")
