mutate (0,"A",1,"","CYS")
set_residue_to_rotamer_name (0,"A",1,"","","p")
write_pdb_file (0,"/home/jbruno/PycharmProjects/SLIDER/aa/CYS/CYS_p.pdb")
set_residue_to_rotamer_name (0,"A",1,"","","t")
write_pdb_file (0,"/home/jbruno/PycharmProjects/SLIDER/aa/CYS/CYS_t.pdb")
set_residue_to_rotamer_name (0,"A",1,"","","m")
write_pdb_file (0,"/home/jbruno/PycharmProjects/SLIDER/aa/CYS/CYS_m.pdb")
